# Generated by Django 4.2.4 on 2023-09-06 22:18

from django.db import migrations
import wagtailmarkdown.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='body',
            field=wagtailmarkdown.fields.MarkdownField(blank=True),
        ),
    ]
