# Generated by Django 4.2.4 on 2023-09-06 23:02

from django.db import migrations
import wagtailmarkdown.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_blogpage_markdown'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='markdown',
            field=wagtailmarkdown.fields.MarkdownField(blank=True),
        ),
    ]
